# Generated by Django 5.2 on 2025-05-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('usuario', '0002_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('fantasy_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'enterprise',
                'verbose_name_plural': 'enterprises',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(auto_now_add=True)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='functions', to='usuario.employer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.position')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employers', to='usuario.employer')),
            ],
            options={
                'verbose_name': 'function',
                'verbose_name_plural': 'functions',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='core.enterprise')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
    ]
