# Generated by Django 5.2 on 2025-05-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enterprise_function_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telephone',
            options={'verbose_name': 'telephone', 'verbose_name_plural': 'telephones'},
        ),
        migrations.AddField(
            model_name='function',
            name='sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.sector'),
        ),
        migrations.AddField(
            model_name='telephone',
            name='enterprise_phone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.enterprise'),
        ),
        migrations.AddField(
            model_name='telephone',
            name='user_phone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
