# Generated by Django 5.2 on 2025-05-09 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_telephone_options_function_sector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='functions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='function',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employers', to=settings.AUTH_USER_MODEL),
        ),
    ]
