# Generated by Django 5.2 on 2025-05-14 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_function_employer_alter_function_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('next_evaluation_date', models.DateField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluated', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliation',
                'verbose_name_plural': 'Avaliations',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('enterprise_topic', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.enterprise')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TopicAvaliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('avaliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_avaliations', to='core.avaliation')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_avaliations', to='core.topic')),
            ],
            options={
                'verbose_name': 'Topic Avaliation',
                'verbose_name_plural': 'Topics Avaliations',
                'ordering': ['topic'],
            },
        ),
    ]
