# Generated by Django 5.2 on 2025-05-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_avaliation_topic_topicavaliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicavaliation',
            name='avaliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topic_avaliations', to='core.avaliation'),
        ),
    ]
