# Generated by Django 5.2 on 2025-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_topicavaliation_avaliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
