# Generated by Django 5.2 on 2025-06-09 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_telephone_user_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='function',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position', to='core.position'),
        ),
        migrations.AlterField(
            model_name='function',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
