# Generated by Django 5.2 on 2025-05-05 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=100, unique=True)),
                ('photo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employer',
                'verbose_name_plural': 'employers',
                'ordering': ['-id'],
            },
        ),
    ]
