# Generated by Django 5.2 on 2025-05-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_telephone_options_function_sector_and_more'),
        ('usuario', '0002_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='employer',
            name='enterprise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.enterprise'),
        ),
    ]
