# Generated by Django 5.2 on 2025-05-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_function_employer_alter_function_supervisor'),
        ('uploader', '0001_initial'),
        ('usuario', '0003_remove_usuario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.AddField(
            model_name='usuario',
            name='enterprise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.enterprise'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='registration',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
