# Generated by Django 5.2 on 2025-05-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_function_employer_alter_function_supervisor'),
        ('usuario', '0004_remove_usuario_cpf_usuario_enterprise_usuario_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='enterprise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.enterprise'),
        ),
    ]
