# Generated by Django 5.2 on 2025-05-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='registration',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
