# Generated by Django 5.2 on 2025-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='media',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
